Iterating GH Action Mon Jan  6 03:17:23 PM EST 2025

diff --git a/.github/workflows/deploy-to-dev.yaml b/.github/workflows/deploy-to-dev.yaml
--- a/.github/workflows/deploy-to-dev.yaml
+++ b/.github/workflows/deploy-to-dev.yaml
@@ -91,18 +91,17 @@ jobs:
       - name: TF init
         run: |
           pushd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
-            terraform init -reconfigure -backend-config="./backend_${{ inputs.environment }}.config" || echo "Failed" && exit
+            terraform init -backend-config="./backend_${{ inputs.environment }}.config" || echo "Failed" && exit
           popd
 
       - name: TF plan
-        run: |
-          pushd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
-            make plan
-          popd
+        uses:  dflook/terraform-plan@v1
+        with:
+          path: ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
+          backend_config_file: "${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}/backend_${{ inputs.environment}}.config"
 
-      - name: TF apply
-        run: |
-          pushd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
-            make apply
-          popd
-  
+      # - name: TF apply
+      # run: |
+      #   pushd ${GITHUB_WORKSPACE}/terraform/${{ inputs.environment }}
+      #     make apply
+      #   popd
